[package]
name = "caller"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
callee-interface = { path = "../callee-interface" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
callee = { path = "../callee" }
